### ISSUE TITLE
Problem compiling a C program into BPF

### ISSUE THREAD

**Issue by johhnsmmith198** [masmullin2000/libbpf-sample#1]
Hi Michael, 
I watch your video online and I was wondering if you could help me with my issue bellow:

https://github.com/nmandery/h3ron/issues/30#issuecomment-1019858644

Ultimately I just want to add the h3ron library as a dependency of a rust program that needs to build-bpf for solana.

The problem is not so much related to Rust but it is related to build the h3ron-h3-sys/libh3 library with cmake for solana.

Please can you help?

**Comment by masmullin2000** [comment]
It seems you're having problems linking.  Linking bpf is extremely new, and I've never played with it before.

https://github.com/aya-rs/bpf-linker

I'd check out that project and see if you can get it into the cmake builder of h3ron.  I expect that even if you can get a linker working, h3ron is far to large for the bpf stack, but it sounds like an interesting experiment.

Please close this issue as it has nothing to do with these samples for libbpf.

**Comment by johhnsmmith198** [comment]
Hey @masmullin2000 thank you so much. Yes this is not really an issue. I was trying to reach you.
I will close it immediately, thanks for your help.
