### ISSUE TITLE
Error in makefile

### ISSUE THREAD

**Issue by sheharyaar** [masmullin2000/libbpf-sample#2]
Hi @masmullin2000 , after running make run in `simple` folder, i get the following error:

```
bpftool btf dump file /sys/kernel/btf/vmlinux format c > vmlinux.h
clang -O3 -target bpf -D__TARGET_ARCH_x86_64 -c exec.bpf.c -o exec.bpf.o
bpftool gen skeleton exec.bpf.o name exec > exec.skel.h
clang exec.c -lbpf -lelf -o exec
In file included from exec.c:5:
./exec.skel.h:132:37: error: no member named 'rodata' in 'struct exec'
        s->maps[0].mmaped = (void **)&obj->rodata;
                                      ~~~  ^
1 error generated.
make: *** [Makefile:5: exec] Error 1
```

**Comment by masmullin2000** [comment]
Not sure why but bpftool isn't generating a proper skeleton.  I've updated the Makefile so that the skeleton is touched up and made 'to work'.

Note: seems newer bpftool will segfault due to a null pointer deref (linux kernel mainline as of May 23, 2022).

**Comment by masmullin2000** [comment]
Please retest with ba5a519a3a3edcb12b7d2403af9c1018c3001c0c (or latest code)

**Comment by sheharyaar** [comment]
Works! Thanks for the instant reply!
