### ISSUE TITLE
libbpf-example on Ubuntu 18.04

### ISSUE THREAD

**Issue by AsherAroussi** [masmullin2000/libbpf-sample#3]
Hi.

I'm trying to compile the simple example and fail.
It looks like bpftool is not part of linux-tools-common and I need to install it manually.

Installation steps:
git clone --recurse-submodules https://github.com/libbpf/bpftool.git
cd bpftool/src
make -j$(nproc)

When I try to compile, I get this error:

make
bpftool btf dump file /sys/kernel/btf/vmlinux format c > vmlinux.h
Usage: /usr/lib/linux-tools/4.15.0-213-generic/bpftool [OPTIONS] OBJECT { COMMAND | help }
       /usr/lib/linux-tools/4.15.0-213-generic/bpftool batch file FILE
       /usr/lib/linux-tools/4.15.0-213-generic/bpftool version

       OBJECT := { prog | map }
       OPTIONS := { {-j|--json} [{-p|--pretty}] | {-f|--bpffs} }
Makefile:25: recipe for target 'vmlinux' failed
make: *** [vmlinux] Error 255

My kernel version is 4.15.0-213 and it lacks the file /sys/kernel/btf/vmlinux.

Is this simple project can be compiled and run under Ubuntu 18.04 / Kernel 4.15.0-213 ?

Thanks.

**Comment by masmullin2000** [comment]
simple is probably "simple" enough to remove the dependency on #include "vmlinux.h" which would alleviate the need to create it.  You would also need to change the bpf_printk to bpf_trace_printk (see: https://man7.org/linux/man-pages/man7/bpf-helpers.7.html)

In the end however, you are probably going to need to downgrade from using libbpf to using the bcc compiler and it's associated tools if you lack BTF functionality.

https://github.com/iovisor/bcc

So... the plain answer is "no you cannot use this code as-is on 18.04"
